"""Constants for SMA Bluetooth."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "sma_bluetooth"
PLATFORMS = ["sensor", "event"]

CONF_BT_ADDRESS = "bt_address"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_PLANT_NAME = "plant_name"
CONF_KNOWN_INVERTERS = "known_inverters"
CONF_CONNECTION_MODE = "connection_mode"
CONF_NET_ID = "net_id"
CONF_SELECTED_SERIAL = "selected_serial"
CONF_LAST_DETECTED_NET_ID = "last_detected_net_id"
CONF_LAST_DETECTED_SERIALS = "last_detected_serials"

CONNECTION_MODE_AUTO = "auto"
CONNECTION_MODE_SINGLE = "single"
CONNECTION_MODE_NETWORK = "network"
CONNECTION_MODES = (
    CONNECTION_MODE_AUTO,
    CONNECTION_MODE_SINGLE,
    CONNECTION_MODE_NETWORK,
)
DEFAULT_CONNECTION_MODE = CONNECTION_MODE_AUTO

EFFECTIVE_MODE_SINGLE = "single"
EFFECTIVE_MODE_NETWORK = "network"

NETWORK_ROLE_DIRECT = "direct"
NETWORK_ROLE_ROOT = "root_node"
NETWORK_ROLE_PARTICIPANT = "participant"

HUB_IDENTIFIER_PREFIX = "hub_"
DATA_ADAPTER_GATE = "_adapter_gate"

DEFAULT_PLANT_NAME = "SMA PV"
DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 60
UPDATE_TIMEOUT = 45
RFCOMM_RELEASE_DELAY = 5
RFCOMM_SESSION_ATTEMPTS = 3
RFCOMM_RECOVERY_FAILURES = 2
RFCOMM_RECOVERY_COOLDOWN = 30 * 60
MAX_ARCHIVE_DAYS = 62
DEFAULT_UPDATE_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL)
